apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: d3qc04e3n-go-stage
  namespace: rhtap-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/d3qc04e3n-go/overlays/stage
    repoURL: https://github.com/rhtap-rhdh-qe/d3qc04e3n-go-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app-stage
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

